version: '3.9'

services:
  api:
    image: fast-api
    #container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      MONGO_URL: mongodb://root:1234@mongo:27017/
      MONGO_DB_NAME: book-store
    ports:
      - 8000:80
    networks:
      - backend
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    networks:
      - backend
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@mongo:27017/
    networks:
      - backend
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    depends_on:
      - mongo

  #redis:
  #  image: "redis:alpine"

networks:
    backend:

volumes:
  mongodb_data:
  mongodb_config:
